### PR TITLE
Adds documentation folders for each subject + readme

### PR DESCRIPTION
**Pull request by solskinIsak**
pelaz approv is good o/

### CODE REVIEW

**Review by CarolineHoeg — APPROVED** [review]
Approved

**Comment by HelenaLykstoft** [comment]
lotm

**Review by thejamiegc — APPROVED** [review]
looks shit to me

**Comment by HelenaLykstoft** [comment]
> looks shit to me

actually same

**Review by HelenaLykstoft — APPROVED** [review]

**Pull request merged**
